# Problem 4 scikit-learn Classification

In [35]:
import csv
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [2]:
disease_data=[]
csv_reader = csv.reader(open('realdata1/chronic_kidney_disease_full.csv', encoding='utf-8'))
for row in csv_reader:
    disease_data.append(row)
print(len(disease_data[1:]))
print(disease_data[0:2])
arr=np.array(disease_data)
print(arr)

400
[['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wbcc', 'rbcc', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'class'], ['48', '80', '1.020', '1', '0', '?', 'normal', 'notpresent', 'notpresent', '121', '36', '1.2', '?', '?', '15.4', '44', '7800', '5.2', 'yes', 'yes', 'no', 'good', 'no', 'no', 'ckd']]
[['age' 'bp' 'sg' ..., 'pe' 'ane' 'class']
 ['48' '80' '1.020' ..., 'no' 'no' 'ckd']
 ['7' '50' '1.020' ..., 'no' 'no' 'ckd']
 ..., 
 ['12' '80' '1.020' ..., 'no' 'no' 'notckd']
 ['17' '60' '1.025' ..., 'no' 'no' 'notckd']
 ['58' '80' '1.025' ..., 'no' 'no' 'notckd']]


In [57]:
# Delete all the rows which contain missing values
# Replace all the nominal data with 0 and 1

dis_data=[]
dis_data.append(disease_data[0])
for i in range(1,len(disease_data)):
    w=True
    for j in range(len(disease_data[i])):
        if(disease_data[i][j]=='?'):
            w=False
            break
    if w:
        dis_data.append(disease_data[i])
print(len(dis_data[1:]))
print(dis_data[0:3])

dis_data2=[]
dis_data2.append(dis_data[0])
for i in range(1,len(dis_data)):
    line=dis_data[i]
    for j in range(len(line)):
        if line[j]=='normal':
            line[j]='0'
        elif(line[j]=='abnormal'):
            line[j]='1'
        elif(line[j]=='present'):
            line[j]='0'
        elif(line[j]=='notpresent'):
            line[j]='1'
        elif(line[j]=='yes'):
            line[j]='0'
        elif(line[j]=='no'):
            line[j]='1'
        elif(line[j]=='good'):
            line[j]='0'
        elif(line[j]=='poor'):
            line[j]='1'
        elif(line[j]=='ckd'):
            line[j]='0'
        elif(line[j]=='notckd'):
            line[j]='1'
        line[j]=float(line[j])
    dis_data2.append(line)

print(len(dis_data2[1:]))
print(dis_data2[0:3])


158
[['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wbcc', 'rbcc', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'class'], [48.0, 70.0, 1.005, 4.0, 0.0, 0.0, 1.0, 0.0, 1.0, 117.0, 56.0, 3.8, 111.0, 2.5, 11.2, 32.0, 6700.0, 3.9, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0], [53.0, 90.0, 1.02, 2.0, 0.0, 1.0, 1.0, 0.0, 1.0, 70.0, 107.0, 7.2, 114.0, 3.7, 9.5, 29.0, 12100.0, 3.7, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0]]
158
[['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wbcc', 'rbcc', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'class'], [48.0, 70.0, 1.005, 4.0, 0.0, 0.0, 1.0, 0.0, 1.0, 117.0, 56.0, 3.8, 111.0, 2.5, 11.2, 32.0, 6700.0, 3.9, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0], [53.0, 90.0, 1.02, 2.0, 0.0, 1.0, 1.0, 0.0, 1.0, 70.0, 107.0, 7.2, 114.0, 3.7, 9.5, 29.0, 12100.0, 3.7, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0]]


In [20]:
from sklearn.model_selection import train_test_split
xx=[]
yy=[]
for i in range(1,len(dis_data2)):
    xx.append(dis_data2[i][:-1])
    yy.append(dis_data2[i][-1])
X=np.array(xx)
y=np.array(yy)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(len(X_train))
print(len(y_train))
print(len(X_test))
print(len(y_test))

126
126
32
32


In [55]:
# Support Vector Machine with the linear kernel and default parameters

from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

clf_linearSVC = SVC(kernel='linear')
clf_linearSVC.fit(X_train, y_train) 
y_pred_train= clf_linearSVC.predict(X_train)
y_pred_test= clf_linearSVC.predict(X_test)

cf_train = confusion_matrix(y_train, y_pred_train)
TN, FP, FN, TP = cf_train.ravel()
Pre=TP/(TP+FP)
Rec=TP/(TP+FN)
f_measure= 2*Pre*Rec/(Pre+Rec)
print('train:')
print(cf_train)
print(f_measure)

cf_test = confusion_matrix(y_test, y_pred_test)
TN, FP, FN, TP = cf_test.ravel()
Pre=TP/(TP+FP)
Rec=TP/(TP+FN)
f_measure= 2*Pre*Rec/(Pre+Rec)
print('test:')
print(cf_test)
print(f_measure)

train:
[[34  0]
 [ 0 92]]
1.0
test:
[[ 8  1]
 [ 0 23]]
0.978723404255


In [54]:
# Support Vector Machine with the RBF kernel and default parameters

clf_rbfSVC = SVC(kernel='rbf')
clf_rbfSVC.fit(X_train, y_train) 
y_pred_train= clf_rbfSVC.predict(X_train)
y_pred_test= clf_rbfSVC.predict(X_test)

cf_train = confusion_matrix(y_train, y_pred_train)
TN, FP, FN, TP = cf_train.ravel()
Pre=TP/(TP+FP)
Rec=TP/(TP+FN)
f_measure= 2*Pre*Rec/(Pre+Rec)
print('train:')
print(cf_train)
print(f_measure)

cf_test = confusion_matrix(y_test, y_pred_test)
TN, FP, FN, TP = cf_test.ravel()
Pre=TP/(TP+FP)
Rec=TP/(TP+FN)
f_measure= 2*Pre*Rec/(Pre+Rec)
print('test:')
print(cf_test)
print(f_measure)

train:
[[34  0]
 [ 0 92]]
1.0
test:
[[ 0  9]
 [ 0 23]]
0.836363636364


In [53]:
# Random forest with default parameters (sklearn.ensemble.RandomForestClassifier)

from sklearn.ensemble import RandomForestClassifier
clf_RF = RandomForestClassifier()
clf_RF.fit(X_train, y_train) 
y_pred_train = clf_RF.predict(X_train)
y_pred_test = clf_RF.predict(X_test)

cf_train = confusion_matrix(y_train, y_pred_train)
TN, FP, FN, TP = cf_train.ravel()
Pre=TP/(TP+FP)
Rec=TP/(TP+FN)
f_measure= 2*Pre*Rec/(Pre+Rec)
print('train:')
print(cf_train)
print(f_measure)

cf_test = confusion_matrix(y_test, y_pred_test)
TN, FP, FN, TP = cf_test.ravel()
Pre=TP/(TP+FP)
Rec=TP/(TP+FN)
f_measure= 2*Pre*Rec/(Pre+Rec)
print('test:')
print(cf_test)
print(f_measure)

train:
[[34  0]
 [ 0 92]]
1.0
test:
[[ 9  0]
 [ 0 23]]
1.0
