# Problem 3 scikit-learn Clustering

In [186]:
import sklearn.cluster
from sklearn.metrics import confusion_matrix
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.datasets import load_digits
from sklearn.preprocessing import scale
from sklearn.metrics.cluster import fowlkes_mallows_score

In [123]:
digits = load_digits()
print(digits.data.shape)
print(digits.data)


(1797, 64)
[[  0.   0.   5. ...,   0.   0.   0.]
 [  0.   0.   0. ...,  10.   0.   0.]
 [  0.   0.   0. ...,  16.   9.   0.]
 ..., 
 [  0.   0.   1. ...,   6.   0.   0.]
 [  0.   0.   2. ...,  12.   0.   0.]
 [  0.   0.  10. ...,  12.   1.   0.]]


In [221]:
labels=digits.target
print(len(labels))
print(labels)
y_true= labels
y_t=[]
for i in range(len(y_true)):
    y_t.append(y_true[i])
#print(y_t)

1797
[0 1 2 ..., 8 9 8]


In [230]:

class Kmean:
    def __init__(self, data ,c_num, itor):
        self.data= data
        self.length= np.array(data).shape[0]
        self.dim= np.array(data).shape[1]
        self.c_num= c_num
        self.itoration= itor
    
    def Eu_dist(self, x, y):
        if(len(x)!=len(y)):
            return False
        sum=0
        for i in range(len(x)):
            sum+= pow(x[i]-y[i],2)
        
        return math.sqrt(sum)
    
    def rand_centroid(self):
        maxv=[-999999]*self.dim
        minv=[999999]*self.dim
        for i in range(len(self.data)):
            for j in range(len(self.data[i])):
                if self.data[i][j] >= maxv[j]:
                    maxv[j]=self.data[i][j]
                if self.data[i][j] <= minv[j]:
                    minv[j]=self.data[i][j]
        #print(maxv)
        #print(minv)
        rand_cent=[]
        for i in range(self.c_num):
            temp=[]
            for j in range(self.dim):
                x=random.uniform(minv[j],maxv[j])
                temp.append(x)
            rand_cent.append(temp)    
        #print(rand_c)
        return rand_cent
    
    def kmean(self, data, centroids):
        for i in range(self.itoration):
            y_pred=[]
            for j in range(len(data)):
                odis=999999
                cluster=0
                for k in range(len(centroids)):
                    if(self.Eu_dist(data[j], centroids[k])<odis):
                        odis= self.Eu_dist(data[j], centroids[k])
                        cluster=k
                y_pred.append(cluster)
            #print(y_pred)
            
            self.draw_graph(data, y_pred, centroids)
            
            sum_c=[[0]*self.dim for w in range(len(centroids))]
            num_c=[0]*len(centroids)
            
            for j in range(len(y_pred)):
                num_c[y_pred[j]]+=1
                for k in range(self.dim):
                    sum_c[y_pred[j]][k]+=data[j][k]
            new_cnum=0
            avg_c=[]
            for j in range(len(centroids)):
                if(num_c[j]>0):
                    temp=[]
                    for k in range(self.dim):
                        temp.append(sum_c[j][k]/num_c[j])
                    avg_c.append(temp)
                    new_cnum+=1
            #print(new_cnum)
            print(centroids)
            #print(avg_c)
            
            if new_cnum==len(centroids):
                coverge_dis=0
                for j in range(len(centroids)):
                    coverge_dis+= self.Eu_dist(centroids[j],avg_c[j])
                #print(coverge_dis)
                if coverge_dis<=0.05:
                    return avg_c
         
            centroids=avg_c.copy()
            
        return avg_c
                

                

In [222]:

y_pred= sklearn.cluster.k_means(scale(digits.data), 10)[1].tolist()
#print(y_pred)
y_count=[[0]*10 for k in range(10)]

for i in range(len(y_pred)):
    y_count[y_pred[i]][y_true[i]]+=1

y_pred2=[]
for i in range(len(y_count)):
    y_pred2.append(y_count[i].index(max(y_count[i])))
#print(y_pred2)

y_pred_cluster=[]
for i in range(len(y_pred)):
    y_pred_cluster.append(y_pred2[y_pred[i]])

result= confusion_matrix(y_true, y_pred_cluster)
relist= result.tolist()


for i in range(len(relist)):
    ct=0
    for j in range(len(relist)):
        if(relist[j][i]==0):
            ct+=1
    if ct==10:
        for j in range(len(relist)):
            relist[j][i]=-1

conf_matrix = np.array(relist)
print(conf_matrix)

from sklearn.metrics.cluster import fowlkes_mallows_score
fowlkes_mallows_score(y_t, y_pred_cluster)

[[177   0   0   0   1  -1   0   0   0  -1]
 [  0  58  27   0   0  -1   0   1  96  -1]
 [  0   5 131   3   1  -1   0   2  35  -1]
 [  0   0  15 151   0  -1   0   8   9  -1]
 [  0   7   0   0 157  -1   0  13   4  -1]
 [  0   2  40  71   2  -1   3   2  62  -1]
 [  1   1   0   0   0  -1 175   0   4  -1]
 [  0   3   7   0   0  -1   0 169   0  -1]
 [  0  17   8  47   0  -1   3   2  97  -1]
 [  0  19   0 145   0  -1   0  11   5  -1]]


In [226]:
#Agglomerative clustering with Ward linkage
from sklearn.cluster import AgglomerativeClustering
model_AC = AgglomerativeClustering(linkage='ward', n_clusters=10)
y_pred_AC= model_AC.fit_predict(digits.data)
#print(y_pred_AC)

y_count_AC=[[0]*10 for k in range(10)]

for i in range(len(y_pred_AC)):
    y_count_AC[y_pred_AC[i]][y_true[i]]+=1
    
y_pred2=[]
for i in range(len(y_count_AC)):
    y_pred2.append(y_count_AC[i].index(max(y_count_AC[i])))

y_pred_cluster=[]
for i in range(len(y_pred_AC)):
    y_pred_cluster.append(y_pred2[y_pred_AC[i]])

result= confusion_matrix(y_true, y_pred_cluster)
relist= result.tolist()

for i in range(len(relist)):
    ct=0
    for j in range(len(relist)):
        if(relist[j][i]==0):
            ct+=1
    if ct==10:
        for j in range(len(relist)):
            relist[j][i]=-1

conf_matrix = np.array(relist)
print(conf_matrix)

fowlkes_mallows_score(y_t, y_pred_cluster)

[[178   0   0   0   0   0   0   0   0  -1]
 [  0 155  27   0   0   0   0   0   0  -1]
 [  0   0 166   0   0   0   0   1  10  -1]
 [  0   0   0 169   0   0   0   1  13  -1]
 [  0   0   0   0 178   0   0   3   0  -1]
 [  0   0   0   2   0 179   1   0   0  -1]
 [  0   0   0   0   0   0 180   0   1  -1]
 [  0   0   0   0   0   0   0 179   0  -1]
 [  0   3   4   1   0   0   0   1 165  -1]
 [  0  20   0 145   0   2   0  11   2  -1]]


In [195]:
len(y_true)

1797

In [196]:
len(y_pred_cluster)

1797

In [211]:
# AffinityPropagation
from sklearn.cluster import AffinityPropagation
model_AP = AffinityPropagation()
y_pred_AP = model_AP.fit_predict(digits.data)
#print(y_pred_AP)

maxlen= max(y_pred_AP)
y_count_AP=[[0]*10 for k in range(maxlen+1)]

for i in range(len(y_pred_AP)):
    y_count_AP[y_pred_AP[i]][y_true[i]]+=1
    
y_pred2=[]
for i in range(len(y_count_AP)):
    y_pred2.append(y_count_AP[i].index(max(y_count_AP[i])))

y_pred_cluster=[]
for i in range(len(y_pred_AP)):
    y_pred_cluster.append(y_pred2[y_pred_AP[i]])

result= confusion_matrix(y_true, y_pred_cluster)
relist= result.tolist()

for i in range(len(relist)):
    ct=0
    for j in range(len(relist)):
        if(relist[j][i]==0):
            ct+=1
    if ct==10:
        for j in range(len(relist)):
            relist[j][i]=-1

conf_matrix = np.array(relist)
print(conf_matrix)

fowlkes_mallows_score(y_t, y_pred_cluster)

[[177   0   0   0   1   0   0   0   0   0]
 [  0 182   0   0   0   0   0   0   0   0]
 [  0   0 176   1   0   0   0   0   0   0]
 [  0   0   0 177   0   2   0   0   0   4]
 [  0   4   0   0 171   0   0   4   0   2]
 [  0   0   0   0   0 180   0   0   0   2]
 [  2   1   0   0   0   0 178   0   0   0]
 [  0   0   0   0   0   0   0 178   0   1]
 [  0  16   2   3   0   1   1   1 149   1]
 [  0   1   0   0   0   3   0   1   1 174]]
